"""
=============================================================================
NUVI - Text Preprocessing Module
=============================================================================
Academic Context (AI & Machine Learning Syllabus):
Before machine learning models (like Logistic Regression) can process natural 
language, raw text must undergo "Text Preprocessing" / "Text Normalization".

Why Preprocessing Matters:
1. Normalization: "Open Chrome" and "open  chrome!" should represent the exact
   same semantic instruction. Without normalization, a machine learning model
   would treat capitalized, punctuated, or irregularly-spaced strings as 
   distinct tokens.
2. Noise Reduction: Removing arbitrary punctuation and surplus whitespace
   reduces the vocabulary space and prevents sparse matrix inflation.
3. Simplicity: Keeping the pipeline lightweight (lowercasing, punctuation 
   stripping, whitespace collapsing) avoids brittle over-engineering while 
   remaining fast and interpretable.
=============================================================================
"""

import re
import string
import pandas as pd


def clean_text(text: str) -> str:
    """
    Cleans and normalizes a single string input.

    Steps:
    1. Convert all characters to lowercase (case normalization).
    2. Strip leading and trailing whitespace.
    3. Remove punctuation characters (e.g. '!', '?', ',', '.') while preserving
       alphanumerics and intra-word hyphens/underscores where appropriate.
    4. Collapse multiple consecutive whitespace characters into a single space.

    Args:
        text (str): The raw text command.

    Returns:
        str: Normalized, lowercase text string.
    """
    if not isinstance(text, str):
        return ""

    # Step 1: Lowercase conversion
    normalized = text.lower().strip()

    # Step 2: Remove punctuation
    # We replace punctuation with spaces to avoid concatenating words (e.g., "report.pdf" -> "report pdf")
    # For file extensions or simple commands, separating punctuation helps TF-IDF tokenize roots.
    punctuation_pattern = f"[{re.escape(string.punctuation)}]"
    normalized = re.sub(punctuation_pattern, " ", normalized)

    # Step 3: Collapse redundant whitespaces into a single space
    normalized = re.sub(r"\s+", " ", normalized).strip()

    return normalized


def preprocess_dataset(df: pd.DataFrame, text_column: str = "command", label_column: str = "intent") -> pd.DataFrame:
    """
    Preprocesses a pandas DataFrame containing text commands and labels.

    Steps:
    1. Drop rows with missing values in text or label columns.
    2. Apply text normalization (clean_text) across all commands.
    3. Drop empty strings generated by cleaning.
    4. Remove duplicate entries to prevent data leakage and train/test bias.

    Args:
        df (pd.DataFrame): Raw DataFrame containing commands and labels.
        text_column (str): Name of the column with raw commands.
        label_column (str): Name of the column with intent labels.

    Returns:
        pd.DataFrame: Cleaned and deduplicated DataFrame.
    """
    # Make a copy to avoid mutating the original dataframe
    clean_df = df[[text_column, label_column]].copy()

    # Step 1: Drop missing values (Null / NaN)
    clean_df = clean_df.dropna(subset=[text_column, label_column])

    # Step 2: Normalize the text column
    clean_df[text_column] = clean_df[text_column].astype(str).apply(clean_text)

    # Step 3: Filter out empty strings
    clean_df = clean_df[clean_df[text_column] != ""]

    # Step 4: Drop duplicate commands
    initial_count = len(clean_df)
    clean_df = clean_df.drop_duplicates(subset=[text_column])
    dropped_duplicates = initial_count - len(clean_df)

    if dropped_duplicates > 0:
        print(f"[Preprocessing] Removed {dropped_duplicates} duplicate command entries.")

    return clean_df.reset_index(drop=True)
